### ISSUE TITLE
是否支持Vue作为宿主应用？

### ISSUE THREAD

**Issue by ayiaq1** [aliyun/alibabacloud-alfa#41]
我看packages里面只有react,ng作为宿主应用，目前是否开放了Vue作为宿主应用？

**Comment by Boelroy** [comment]
目前还没有，由于目前还没需求就没做，不过这周可以做一下。

**Comment by Boelroy** [comment]
可以参考如下文档 https://github.com/aliyun/alibabacloud-alfa/blob/master/docs/ecosystem/vue.md
