### ISSUE TITLE
子应用中使用 element.ownerDocument 挂载时，元素会被挂载在父页面 body 下

### ISSUE THREAD

**Issue by Cweili** [aliyun/alibabacloud-alfa#55]
如使用 antd 的 DatePicker 等组件时，元素会被挂载在父页面 body 下。
此时，由于样式被增加了前缀，弹出的日期选择框无法匹配到样式。

源码：
https://github.com/react-component/trigger/blob/4259210ac983f562338c405524f7aed4c4bccd8a/src/index.tsx#L39

文档：
https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

**Comment by Boelroy** [comment]
目前的确没有好的解法。有几种办法 ：

1. 一种是开启 fakeBody. 这样 body 就会被变成 宿主 生成的节点，这样 DatePick 就会被添加到这个节点下面
2. 第二种是这边提供一个忽略 CSS 前缀的配置, 忽略掉子应用中的一些 class

**Comment by Cweili** [comment]
> 目前的确没有好的解法。有几种办法 ：
> 
> 1. 一种是开启 fakeBody. 这样 body 就会被变成 宿主 生成的节点，这样 DatePick 就会被添加到这个节点下面
> 2. 第二种是这边提供一个忽略 CSS 前缀的配置, 忽略掉子应用中的一些 class

开启 fakeBody 这个是如何开启呢

**Comment by Boelroy** [comment]
```javascript
<Application  sandbox={{disableFakeBody: true}} />
```

**Comment by Cweili** [comment]
好的，多谢！
