### ISSUE TITLE
打正式包 需要Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by longkehuawei** [aliyun/alibabacloud-alfa#62]
'http://localhost:6065/urule/res/urule-asserts/js/os-example.manifest.json' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Boelroy** [comment]
可以设置 webpack 的跨域：

```javascript
{
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*',
    }
  }
}
```

**Comment by longkehuawei** [comment]
正式打包怎么办呀

**Comment by longkehuawei** [comment]
devtool: 'source-map',
    devServer: {
        port: '6065',
        clientLogLevel: 'warning',
        disableHostCheck: true,
        compress: true,
        headers: {
            'Access-Control-Allow-Origin': '*',
        },
        overlay: { warnings: false, errors: true },
    },
    mode: 'development',

**Comment by longkehuawei** [comment]
这个是开发环境配置才有用吧，正式打包要怎么弄呢

**Comment by Boelroy** [comment]
> 这个是开发环境配置才有用吧，正式打包要怎么弄呢

正式环境如果部署在 CDN 上都是可以跨域请求的，如果是和后端代码部署在一起的，可以让后端针对静态文件都设置一下跨域头。
