### ISSUE TITLE
example运行起来后报错

### ISSUE THREAD

**Issue by rivers-fighting** [aliyun/alibabacloud-alfa#77]
在master分支下，照着readme运行example，出现如下问题
![image](https://user-images.githubusercontent.com/85326030/132279413-8f0de1ca-33e8-4cff-ad8c-2c9312ee87ba.png)
![image](https://user-images.githubusercontent.com/85326030/132279508-0234909b-9779-4890-bfa7-5b5b6d43129d.png)

**Comment by Boelroy** [comment]
这个也不是 报错 这个就是 react 的一个 warning 可以忽略
